spring:
  application:
    name: fintrack-ai-backend
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /api/v1/swagger/h2-console
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 6969

springdoc:
  api-docs:
    path: /api/v1/swagger/api-docs
  swagger-ui:
    path: /api/v1/swagger/swagger-ui.html

jwt:
    secret: ${JWT_SECRET:this-is-a-very-long-secret-key-for-jwt-authentication-123456}
    access-expiration: ${JWT_ACCESS_EXPIRATION:900}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400}