spring:
  application:
    name: fintrack-ai-backend
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    driverClassName: ${DB_CLASS:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /api/v1/swagger/h2-console
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  config:
    import: optional:file:.env[.properties]

  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        model: ${OLLAMA_CHAT_MODEL:dolphin-phi}
        options:
          temperature: 0.0

  cache:
    redis:
      time-to-live: 3600s
      cache-null-values: false
      use-key-prefix: true


server:
  port: ${SERVER_PORT:8080}

springdoc:
  api-docs:
    path: /api/v1/swagger/api-docs
  swagger-ui:
    path: /api/v1/swagger/swagger-ui.html

jwt:
    secret: ${JWT_SECRET:this-is-a-very-long-secret-key-for-jwt-authentication-123456}
    access-expiration: ${JWT_ACCESS_EXPIRATION:900}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400}

nlp:
  ollama:
    timeout-seconds: 25
    enabled: true
  fallback:
      enabled: true                # OpenNLP rule-based fallback
  prefilter:
      min-text-length: 3
      max-text-length: 500

